package com.yuzee.common.lib.enumeration;

public enum ApiUniqueNameEnum {
	
	CREATE_EVENT,
	DELETE_EVENT,
	UPDATE_EVENT,
	UPDATE_EVENT_STATUS,
	UPDATE_EVENT_PRIVACY,
	UPDATE_MASTER_EVENT_PRIVACY,
	GET_EVENT_PRIVACY,
	INVITE_USER_TO_EVENT,
	CHANGE_EVENT_INVITATION_STATUS,
	ADMIN_CHANGE_EVENT_INVITATION_STATUS,
	USER_BASED_ON_EVENT_INVITATION,
	USER_BASED_ON_EVENT_INVITATION_PAGINATED,
	GET_ALL_ENTITY_EVENTS_PAGINATED,
	GET_ALL_SELF_EVENTS,
	GET_EVENT_BY_ID,
	GET_EVENTS_BY_IDS
	

}
