package com.yuzee.common.lib.enumeration;

public enum EventType {
	EVENT_TYPE_PUSH_NOTIFICATION("EVENT_TYPE_PUSH_NOTIFICATION"),
	EVENT_TYPE_EMAIL_NOTIFICATION("EVENT_TYPE_EMAIL_NOTIFICATION"),
	EVENT_TYPE_NOTIFICATION("EVENT_TYPE_NOTIFICATION"),
	EVENT_TYPE_EMAIL_UPDATE_REQUEST("EVENT_TYPE_EMAIL_UPDATE_REQUEST"),
	EVENT_TYPE_STORAGE_CREATED("EVENT_TYPE_STORAGE_CREATED"),
	EVENT_TYPE_SAVE_UPDATE_COURSE("EVENT_TYPE_SAVE_UPDATE_COURSE"),
	EVENT_TYPE_SAVE_UPDATE_JOB("EVENT_TYPE_SAVE_UPDATE_JOB"),
	EVENT_TYPE_SAVE_UPDATE_INSTITUTE("EVENT_TYPE_SAVE_UPDATE_INSTITUTE"),
	EVENT_TYPE_CREATE_USER("EVENT_TYPE_CREATE_USER"),
	EVENT_TYPE_SAVE_BASIC_USER_INFORMATION("EVENT_TYPE_SAVE_BASIC_USER_INFORMATION"),
	EVENT_TYPE_SAVE_ADDITIONAL_USER_INFORMATION("EVENT_TYPE_SAVE_ADDITIONAL_USER_INFORMATION"),
	EVENT_TYPE_ACTIVATE_USER("EVENT_TYPE_ACTIVATE_USER"),
	EVENT_TYPE_DEACTIVATE_USER("EVENT_TYPE_DEACTIVATE_USER"),
	EVENT_TYPE_SAVE_UPDATE_FACULTY("EVENT_TYPE_SAVE_UPDATE_FACULTY"),
	EVENT_TYPE_SAVE_UPDATE_LEVEL("EVENT_TYPE_SAVE_UPDATE_LEVEL"),
	EVENT_TYPE_SAVE_UPDATE_ARTICLE("EVENT_TYPE_SAVE_UPDATE_ARTICLE"),
	EVENT_TYPE_SAVE_UPDATE_SCHOLARSHIP("EVENT_TYPE_SAVE_UPDATE_SCHOLARSHIP"),
	EVENT_TYPE_SAVE_UPDATE_NETWORK("EVENT_TYPE_SAVE_UPDATE_NETWORK"),
	EVENT_TYPE_DELETE_NETWORK("EVENT_TYPE_DELETE_NETWORK"),
	EVENT_TYPE_SAVE_UPDATE_COMPANY("EVENT_TYPE_SAVE_UPDATE_COMPANY"),
	EVENT_TYPE_UPDATE_USER_PROFILE_PICTURE("EVENT_TYPE_UPDATE_USER_PROFILE_PICTURE"),
	EVENT_TYPE_DELETE_USER_PROFILE_PICTURE("EVENT_TYPE_DELETE_USER_PROFILE_PICTURE"),
	EVENT_TYPE_SAVE_POST("EVENT_TYPE_SAVE_POST"),
	EVENT_TYPE_UPDATE_POST("EVENT_TYPE_UPDATE_POST"),
	EVENT_TYPE_DELETE_POST("EVENT_TYPE_DELETE_POST"),
	EVENT_TYPE_SAVE_UPDATE_EVENT("EVENT_TYPE_SAVE_UPDATE_EVENT"),
	EVENT_TYPE_DELETE_EVENT("EVENT_TYPE_DELETE_EVENT"),
	EVENT_TYPE_ADD_LIKE("EVENT_TYPE_ADD_LIKE"),
	EVENT_TYPE_ADD_VOTE("EVENT_TYPE_ADD_VOTE"),
	EVENT_TYPE_INTERACTION_DELETE_REACTION_VOTE("EVENT_TYPE_INTERACTION_DELETE_REACTION_VOTE"),
	EVENT_TYPE_INTERACTION_DELETE_LIKE_REACTION("EVENT_TYPE_INTERACTION_DELETE_LIKE_REACTION"),
	EVENT_TYPE_INTERACTION_UPDATE_COMMENT("EVENT_TYPE_INTERACTION_UPDATE_COMMENT"),
	EVENT_TYPE_INTERACTION_DELETE_COMMENT("EVENT_TYPE_INTERACTION_DELETE_COMMENT");
	
	private String name;

	EventType(String name) {
        this.name = name;
    }
	
	public String getName() {
        return this.name;
    }
}
