package com.yuzee.common.lib.enumeration;

public enum EventType {
	EVENT_TYPE_PUSH_NOTIFICATION("EVENT_TYPE_PUSH_NOTIFICATION"),
	EVENT_TYPE_EMAIL_NOTIFICATION("EVENT_TYPE_EMAIL_NOTIFICATION"),
	EVENT_TYPE_NOTIFICATION("EVENT_TYPE_NOTIFICATION"),
	EVENT_TYPE_EMAIL_UPDATE_REQUEST("EVENT_TYPE_EMAIL_UPDATE_REQUEST"),
	EVENT_TYPE_STORAGE_CREATED("EVENT_TYPE_STORAGE_CREATED"),
	EVENT_TYPE_SAVE_UPDATE_COURSE("EVENT_TYPE_SAVE_UPDATE_COURSE"),
	EVENT_TYPE_SAVE_UPDATE_INSTITUTE("EVENT_TYPE_SAVE_UPDATE_INSTITUTE"),
	EVENT_TYPE_SAVE_UPDATE_USER("EVENT_TYPE_SAVE_UPDATE_USER"),
	EVENT_TYPE_SAVE_UPDATE_FACULTY("EVENT_TYPE_SAVE_UPDATE_FACULTY"),
	EVENT_TYPE_SAVE_UPDATE_LEVEL("EVENT_TYPE_SAVE_UPDATE_LEVEL"),
	EVENT_TYPE_SAVE_UPDATE_ARTICLE("EVENT_TYPE_SAVE_UPDATE_ARTICLE"),
	EVENT_TYPE_SAVE_UPDATE_SCHOLARSHIP("EVENT_TYPE_SAVE_UPDATE_SCHOLARSHIP"),
	EVENT_TYPE_SAVE_UPDATE_NETWORK("EVENT_TYPE_SAVE_UPDATE_NETWORK"),
	EVENT_TYPE_SAVE_UPDATE_COMPANY("EVENT_TYPE_SAVE_UPDATE_COMPANY");
	
	private String name;

	EventType(String name) {
        this.name = name;
    }
	
	public String getName() {
        return this.name;
    }
}
