package com.yuzee.common.lib.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum TaskNameEnum {
	YUZEE_REVIEW_NOTITFICATION(null,null),
	IS_YUZEE_APPLICATION_OFFER_ACCEPT_OR_REJECT(null, null),
	YUZEE_REVIEW_STUDENT_APPLICATION(ProcedureStepEnum.YUZEE_REVIEW, null), //YUZEE_REVIEW
	APPLICATION_REJECTION_NOTIFICATION(null, null),
	INSTITUTE_REVIEW_NOTITFICATION(null, null),
	IS_INSTITUTE_APPLICATION_OFFER_ACCEPT_OR_REJECT(null, null),
	INSTITUTE_REVIEW_STUDENT_APPLICATION(ProcedureStepEnum.APPLICANT_REVIEWED_BY_INSTITUTION, null), //APPLICANT_REVIEWED_BY_INSTITUTION
	MAKE_AN_OFFER(ProcedureStepEnum.OFFERS_RECEIVED_BY_APPLICANT, UserApplicationStatusEnum.OFFERED),  //OFFERS_RECEIVED_BY_APPLICANT
	STUDENT_REVIEW_NOTITFICATION(null, null),
	WAIT_FOR_STUDENT_ACCEPT_OFFER_LETTER(ProcedureStepEnum.LETTER_OF_OFFER_APPROVED_BY_APPLICANT, null),  //LETTER_OF_OFFER_APPROVED_BY_APPLICANT
	OFFER_ACCEPTED(null, UserApplicationStatusEnum.ACCEPTED),  //LETTER_OF_OFFER_APPROVED_BY_APPLICANT
	REMINDER_1(null, null),
	REMINDER_2(null, null),
	WAIT_FOR_GRACE_PERIOD_TO_COMPLETE(null,  null),
	OFFER_EXPIRED(null,  UserApplicationStatusEnum.EXPIRED),
	NOTIFIY_OFFER_GRACE_PERIOD_TO_COMPLETE(null, null),
	IS_STUDENT_APPLICATION_OFFER_ACCEPT_OR_REJECT(null, null),
	OFFER_REJECTED(null,  UserApplicationStatusEnum.REJECTED),
	OFFER_REJECTION_NOTIFICATION(null, null),
	SCHEDULE_PRE_TRAINING_REVIEW(ProcedureStepEnum.PRE_TRAINING_REVIEW, null), // PRE_TRAINING_REVIEW, ACCEPTED
	WAIT_SCHEDULE_PRE_TRAINING_REVIEW(null, null),
	CONFIREM_TRAINING_ATTENDED(null, null),
	IS_ATTENDED(null, null),
	CONFIRM_IF_CONTINUE(null, null),
	CONTINUE(null, null),
	PAYMENT(ProcedureStepEnum.PAYMENT, UserApplicationStatusEnum.PAYMENT_CONFIRMED), //PAYMENT, WAITING_PAYMENT
	OTHER(ProcedureStepEnum.OTHER, null), //OTHER
	INFO_SESSION(ProcedureStepEnum.INFO_SESSION, null), //INFO_SESSION
	COMPLETED_ENVIROMENT(ProcedureStepEnum.COMPLETED_ENVIRONMENT, UserApplicationStatusEnum.COMPLETED); //COMPLETED_ENVIRONMENT, UserApplicationStatusEnum.COMPLETED
	
	@Getter private ProcedureStepEnum procedureStep;
	
	@Getter private UserApplicationStatusEnum userApplicationStatus;

}
